### ISSUE TITLE
Request for data

### ISSUE THREAD

**Issue by williamagyapong** [PascalJD/copulapopgen#1]
I came across your paper titled, "Copula-based transferable models for synthetic population generation" and this accompanying repository, which is relevant to my PhD dissertation topic. I am studying the methods and trying to replicate the results presented in the referenced paper, and I would be happy if you could make the data available. Thank you!

**Comment by PascalJD** [comment]
Hi William, 

Thanks for your interest in our project. Attached is the data used for the experiments.

Best,
Pascal

[data.zip](https://github.com/PascalJD/copulapopgen/files/15264186/data.zip)

**Comment by williamagyapong** [comment]
Hello Pascal, 

Thank you so much for sharing the data with me. I really appreciate it. 

Thanks again,
William
